USE BaitM8s
GO

CREATE TABLE Zipcode(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	zipcode INT NOT NULL,
	city NVARCHAR(40) NOT NULL
	)

CREATE TABLE PondOwner (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Address NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    PhoneNumber NVARCHAR(20) NOT NULL,
    UserName NVARCHAR(50) NOT NULL,
    PasswordHash NVARCHAR(200) NOT NULL,
	FK_ZipcodeId INT NOT NULL FOREIGN KEY REFERENCES Zipcode(Id)
);

CREATE TABLE FishSpecies(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Species NVARCHAR(30) NOT NULL UNIQUE,
	)

CREATE TABLE FishingSpot(
    Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
    Address NVARCHAR(50) NOT NULL,
 	FK_zipcodeId INT NOT NULL FOREIGN KEY REFERENCES Zipcode(Id),
	Longitude FLOAT NOT NULL,
	Latitude FLOAT NOT NULL,
	StartAvailableHours INT NOT NULL,
	EndAvailableHours INT NOT NULL,
	Capacity INT NOT NULL,
    HandicapFriendly BIT NOT NULL,
	IsAwaitingApproval BIT NOT NULL,
	FK_PondOwnerId INT NOT NULL FOREIGN KEY REFERENCES PondOwner(Id)
);

CREATE TABLE FishSpecies_FishingSpot (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	FK_FishSpeciesId INT NOT NULL FOREIGN KEY REFERENCES FishSpecies(Id),
	FK_FishingSpotId INT NOT NULL FOREIGN KEY REFERENCES FishingSpot(Id)
)

CREATE TABLE Angler (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Address NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    PhoneNumber NVARCHAR(20) NOT NULL,
    UserName NVARCHAR(50) NOT NULL,
    Password NVARCHAR(200) NOT NULL,
	FK_ZipCodeId INT NOT NULL FOREIGN KEY REFERENCES ZipCode(Id),
);

CREATE TABLE Booking (
    Id INT IDENTITY(1,1) PRIMARY KEY,
	Day INT NOT NULL,
	Month INT NOT NULL,
	Year INT NOT NULL,
	WeekNumber INT NOT NULL,
    NumberOfPeople INT NOT NULL,
	StartTime INT NOT NULL,
	EndTime INT NOT NULL,
	FK_AnglerId INT NOT NULL FOREIGN KEY REFERENCES Angler(Id),
	FK_FishingSpotId INT NOT NULL FOREIGN KEY REFERENCES FishingSpot(Id)
);